### ISSUE TITLE
I clicked but still a noob

### ISSUE THREAD

**Issue by max6cn** [vic317yeh/One-Click-to-Be-Pro#13] opened 2016-06-03 03:39 UTC
This needs to be fixed

**Comment by chiunhau** [comment] 2016-06-03 14:43
😄 😄 😄 Just my thought: 
I think the repo name is a little bit misleading. Mastering a programming language doesn't make you a hero. Overall it's just a tool though 😢  The key to a hero is more about your mind: how do you use those existing tools to create something awesome that never happen? how do you change the world by those skills you just mastered? Everyone can speak, but not everyone can be a good novelist. Cheers 🍻

**Comment by btn0s** [comment] 2016-06-03 15:27
@chiunhau the title says nothing about being a hero... it says be pro. You're right, the responsibility is then on you to use those tools for 'good' or 'evil' or, at least, something... no? But this repo doesn't claim to give you that... it's just a list of resources.

**Comment by chiunhau** [comment] 2016-06-03 16:20
@btn0s Haha oh wait...I just found that I totally mistake the title for "to be HERO" until ten second ago!!
How silly I am. But it would be so strange if someone really claims that though XDD

**Comment by jarrydfillmore** [comment] 2016-06-03 21:20
I'm still a noob too! Lol.

**Comment by vicoyeh** [comment] 2016-06-04 19:19
Duplicate of issue #17

**Closed as completed by vicoyeh** 2016-06-04 19:19 UTC
